/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/a-windy-day-fb78f4cc938144e6902dd5cff354d525
title: A Windy Day
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/a_windy_day.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions.animation_0?.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='OSG_Scene'>
        <group
          name='RootNode_(gltf_orientation_matrix)'
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'RootNode (gltf orientation matrix)' }}
        >
          <group
            name='RootNode_(model_correction_matrix)'
            userData={{ name: 'RootNode (model correction matrix)' }}
          >
            <group
              name='sketchfabtimeframe'
              userData={{ name: 'sketchfab.timeframe' }}
            >
              <group scale={[0, 0, 0]}>
                <group name='frame_49' userData={{ name: 'frame_49' }}>
                  <points
                    name='mesh_0'
                    geometry={nodes.mesh_0.geometry}
                    material={nodes.mesh_0.material}
                  />
                  <points
                    name='mesh_1'
                    geometry={nodes.mesh_1.geometry}
                    material={nodes.mesh_1.material}
                  />
                  <points
                    name='mesh_2'
                    geometry={nodes.mesh_2.geometry}
                    material={nodes.mesh_2.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_48' userData={{ name: 'frame_48' }}>
                  <points
                    name='mesh_3'
                    geometry={nodes.mesh_3.geometry}
                    material={nodes.mesh_3.material}
                  />
                  <points
                    name='mesh_4'
                    geometry={nodes.mesh_4.geometry}
                    material={nodes.mesh_4.material}
                  />
                  <points
                    name='mesh_5'
                    geometry={nodes.mesh_5.geometry}
                    material={nodes.mesh_5.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_47' userData={{ name: 'frame_47' }}>
                  <points
                    name='mesh_6'
                    geometry={nodes.mesh_6.geometry}
                    material={nodes.mesh_6.material}
                  />
                  <points
                    name='mesh_7'
                    geometry={nodes.mesh_7.geometry}
                    material={nodes.mesh_7.material}
                  />
                  <points
                    name='mesh_8'
                    geometry={nodes.mesh_8.geometry}
                    material={nodes.mesh_8.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_46' userData={{ name: 'frame_46' }}>
                  <points
                    name='mesh_9'
                    geometry={nodes.mesh_9.geometry}
                    material={nodes.mesh_9.material}
                  />
                  <points
                    name='mesh_10'
                    geometry={nodes.mesh_10.geometry}
                    material={nodes.mesh_10.material}
                  />
                  <points
                    name='mesh_11'
                    geometry={nodes.mesh_11.geometry}
                    material={nodes.mesh_11.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_45' userData={{ name: 'frame_45' }}>
                  <points
                    name='mesh_12'
                    geometry={nodes.mesh_12.geometry}
                    material={nodes.mesh_12.material}
                  />
                  <points
                    name='mesh_13'
                    geometry={nodes.mesh_13.geometry}
                    material={nodes.mesh_13.material}
                  />
                  <points
                    name='mesh_14'
                    geometry={nodes.mesh_14.geometry}
                    material={nodes.mesh_14.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_44' userData={{ name: 'frame_44' }}>
                  <points
                    name='mesh_15'
                    geometry={nodes.mesh_15.geometry}
                    material={nodes.mesh_15.material}
                  />
                  <points
                    name='mesh_16'
                    geometry={nodes.mesh_16.geometry}
                    material={nodes.mesh_16.material}
                  />
                  <points
                    name='mesh_17'
                    geometry={nodes.mesh_17.geometry}
                    material={nodes.mesh_17.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_43' userData={{ name: 'frame_43' }}>
                  <points
                    name='mesh_18'
                    geometry={nodes.mesh_18.geometry}
                    material={nodes.mesh_18.material}
                  />
                  <points
                    name='mesh_19'
                    geometry={nodes.mesh_19.geometry}
                    material={nodes.mesh_19.material}
                  />
                  <points
                    name='mesh_20'
                    geometry={nodes.mesh_20.geometry}
                    material={nodes.mesh_20.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_42' userData={{ name: 'frame_42' }}>
                  <points
                    name='mesh_21'
                    geometry={nodes.mesh_21.geometry}
                    material={nodes.mesh_21.material}
                  />
                  <points
                    name='mesh_22'
                    geometry={nodes.mesh_22.geometry}
                    material={nodes.mesh_22.material}
                  />
                  <points
                    name='mesh_23'
                    geometry={nodes.mesh_23.geometry}
                    material={nodes.mesh_23.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_41' userData={{ name: 'frame_41' }}>
                  <points
                    name='mesh_24'
                    geometry={nodes.mesh_24.geometry}
                    material={nodes.mesh_24.material}
                  />
                  <points
                    name='mesh_25'
                    geometry={nodes.mesh_25.geometry}
                    material={nodes.mesh_25.material}
                  />
                  <points
                    name='mesh_26'
                    geometry={nodes.mesh_26.geometry}
                    material={nodes.mesh_26.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_40' userData={{ name: 'frame_40' }}>
                  <points
                    name='mesh_27'
                    geometry={nodes.mesh_27.geometry}
                    material={nodes.mesh_27.material}
                  />
                  <points
                    name='mesh_28'
                    geometry={nodes.mesh_28.geometry}
                    material={nodes.mesh_28.material}
                  />
                  <points
                    name='mesh_29'
                    geometry={nodes.mesh_29.geometry}
                    material={nodes.mesh_29.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_39' userData={{ name: 'frame_39' }}>
                  <points
                    name='mesh_30'
                    geometry={nodes.mesh_30.geometry}
                    material={nodes.mesh_30.material}
                  />
                  <points
                    name='mesh_31'
                    geometry={nodes.mesh_31.geometry}
                    material={nodes.mesh_31.material}
                  />
                  <points
                    name='mesh_32'
                    geometry={nodes.mesh_32.geometry}
                    material={nodes.mesh_32.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_38' userData={{ name: 'frame_38' }}>
                  <points
                    name='mesh_33'
                    geometry={nodes.mesh_33.geometry}
                    material={nodes.mesh_33.material}
                  />
                  <points
                    name='mesh_34'
                    geometry={nodes.mesh_34.geometry}
                    material={nodes.mesh_34.material}
                  />
                  <points
                    name='mesh_35'
                    geometry={nodes.mesh_35.geometry}
                    material={nodes.mesh_35.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_37' userData={{ name: 'frame_37' }}>
                  <points
                    name='mesh_36'
                    geometry={nodes.mesh_36.geometry}
                    material={nodes.mesh_36.material}
                  />
                  <points
                    name='mesh_37'
                    geometry={nodes.mesh_37.geometry}
                    material={nodes.mesh_37.material}
                  />
                  <points
                    name='mesh_38'
                    geometry={nodes.mesh_38.geometry}
                    material={nodes.mesh_38.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_36' userData={{ name: 'frame_36' }}>
                  <points
                    name='mesh_39'
                    geometry={nodes.mesh_39.geometry}
                    material={nodes.mesh_39.material}
                  />
                  <points
                    name='mesh_40'
                    geometry={nodes.mesh_40.geometry}
                    material={nodes.mesh_40.material}
                  />
                  <points
                    name='mesh_41'
                    geometry={nodes.mesh_41.geometry}
                    material={nodes.mesh_41.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_35' userData={{ name: 'frame_35' }}>
                  <points
                    name='mesh_42'
                    geometry={nodes.mesh_42.geometry}
                    material={nodes.mesh_42.material}
                  />
                  <points
                    name='mesh_43'
                    geometry={nodes.mesh_43.geometry}
                    material={nodes.mesh_43.material}
                  />
                  <points
                    name='mesh_44'
                    geometry={nodes.mesh_44.geometry}
                    material={nodes.mesh_44.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_34' userData={{ name: 'frame_34' }}>
                  <points
                    name='mesh_45'
                    geometry={nodes.mesh_45.geometry}
                    material={nodes.mesh_45.material}
                  />
                  <points
                    name='mesh_46'
                    geometry={nodes.mesh_46.geometry}
                    material={nodes.mesh_46.material}
                  />
                  <points
                    name='mesh_47'
                    geometry={nodes.mesh_47.geometry}
                    material={nodes.mesh_47.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_33' userData={{ name: 'frame_33' }}>
                  <points
                    name='mesh_48'
                    geometry={nodes.mesh_48.geometry}
                    material={nodes.mesh_48.material}
                  />
                  <points
                    name='mesh_49'
                    geometry={nodes.mesh_49.geometry}
                    material={nodes.mesh_49.material}
                  />
                  <points
                    name='mesh_50'
                    geometry={nodes.mesh_50.geometry}
                    material={nodes.mesh_50.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_32' userData={{ name: 'frame_32' }}>
                  <points
                    name='mesh_51'
                    geometry={nodes.mesh_51.geometry}
                    material={nodes.mesh_51.material}
                  />
                  <points
                    name='mesh_52'
                    geometry={nodes.mesh_52.geometry}
                    material={nodes.mesh_52.material}
                  />
                  <points
                    name='mesh_53'
                    geometry={nodes.mesh_53.geometry}
                    material={nodes.mesh_53.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_31' userData={{ name: 'frame_31' }}>
                  <points
                    name='mesh_54'
                    geometry={nodes.mesh_54.geometry}
                    material={nodes.mesh_54.material}
                  />
                  <points
                    name='mesh_55'
                    geometry={nodes.mesh_55.geometry}
                    material={nodes.mesh_55.material}
                  />
                  <points
                    name='mesh_56'
                    geometry={nodes.mesh_56.geometry}
                    material={nodes.mesh_56.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_30' userData={{ name: 'frame_30' }}>
                  <points
                    name='mesh_57'
                    geometry={nodes.mesh_57.geometry}
                    material={nodes.mesh_57.material}
                  />
                  <points
                    name='mesh_58'
                    geometry={nodes.mesh_58.geometry}
                    material={nodes.mesh_58.material}
                  />
                  <points
                    name='mesh_59'
                    geometry={nodes.mesh_59.geometry}
                    material={nodes.mesh_59.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_29' userData={{ name: 'frame_29' }}>
                  <points
                    name='mesh_60'
                    geometry={nodes.mesh_60.geometry}
                    material={nodes.mesh_60.material}
                  />
                  <points
                    name='mesh_61'
                    geometry={nodes.mesh_61.geometry}
                    material={nodes.mesh_61.material}
                  />
                  <points
                    name='mesh_62'
                    geometry={nodes.mesh_62.geometry}
                    material={nodes.mesh_62.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_28' userData={{ name: 'frame_28' }}>
                  <points
                    name='mesh_63'
                    geometry={nodes.mesh_63.geometry}
                    material={nodes.mesh_63.material}
                  />
                  <points
                    name='mesh_64'
                    geometry={nodes.mesh_64.geometry}
                    material={nodes.mesh_64.material}
                  />
                  <points
                    name='mesh_65'
                    geometry={nodes.mesh_65.geometry}
                    material={nodes.mesh_65.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_27' userData={{ name: 'frame_27' }}>
                  <points
                    name='mesh_66'
                    geometry={nodes.mesh_66.geometry}
                    material={nodes.mesh_66.material}
                  />
                  <points
                    name='mesh_67'
                    geometry={nodes.mesh_67.geometry}
                    material={nodes.mesh_67.material}
                  />
                  <points
                    name='mesh_68'
                    geometry={nodes.mesh_68.geometry}
                    material={nodes.mesh_68.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_26' userData={{ name: 'frame_26' }}>
                  <points
                    name='mesh_69'
                    geometry={nodes.mesh_69.geometry}
                    material={nodes.mesh_69.material}
                  />
                  <points
                    name='mesh_70'
                    geometry={nodes.mesh_70.geometry}
                    material={nodes.mesh_70.material}
                  />
                  <points
                    name='mesh_71'
                    geometry={nodes.mesh_71.geometry}
                    material={nodes.mesh_71.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_25' userData={{ name: 'frame_25' }}>
                  <points
                    name='mesh_72'
                    geometry={nodes.mesh_72.geometry}
                    material={nodes.mesh_72.material}
                  />
                  <points
                    name='mesh_73'
                    geometry={nodes.mesh_73.geometry}
                    material={nodes.mesh_73.material}
                  />
                  <points
                    name='mesh_74'
                    geometry={nodes.mesh_74.geometry}
                    material={nodes.mesh_74.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_24' userData={{ name: 'frame_24' }}>
                  <points
                    name='mesh_75'
                    geometry={nodes.mesh_75.geometry}
                    material={nodes.mesh_75.material}
                  />
                  <points
                    name='mesh_76'
                    geometry={nodes.mesh_76.geometry}
                    material={nodes.mesh_76.material}
                  />
                  <points
                    name='mesh_77'
                    geometry={nodes.mesh_77.geometry}
                    material={nodes.mesh_77.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_23' userData={{ name: 'frame_23' }}>
                  <points
                    name='mesh_78'
                    geometry={nodes.mesh_78.geometry}
                    material={nodes.mesh_78.material}
                  />
                  <points
                    name='mesh_79'
                    geometry={nodes.mesh_79.geometry}
                    material={nodes.mesh_79.material}
                  />
                  <points
                    name='mesh_80'
                    geometry={nodes.mesh_80.geometry}
                    material={nodes.mesh_80.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_22' userData={{ name: 'frame_22' }}>
                  <points
                    name='mesh_81'
                    geometry={nodes.mesh_81.geometry}
                    material={nodes.mesh_81.material}
                  />
                  <points
                    name='mesh_82'
                    geometry={nodes.mesh_82.geometry}
                    material={nodes.mesh_82.material}
                  />
                  <points
                    name='mesh_83'
                    geometry={nodes.mesh_83.geometry}
                    material={nodes.mesh_83.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_21' userData={{ name: 'frame_21' }}>
                  <points
                    name='mesh_84'
                    geometry={nodes.mesh_84.geometry}
                    material={nodes.mesh_84.material}
                  />
                  <points
                    name='mesh_85'
                    geometry={nodes.mesh_85.geometry}
                    material={nodes.mesh_85.material}
                  />
                  <points
                    name='mesh_86'
                    geometry={nodes.mesh_86.geometry}
                    material={nodes.mesh_86.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_20' userData={{ name: 'frame_20' }}>
                  <points
                    name='mesh_87'
                    geometry={nodes.mesh_87.geometry}
                    material={nodes.mesh_87.material}
                  />
                  <points
                    name='mesh_88'
                    geometry={nodes.mesh_88.geometry}
                    material={nodes.mesh_88.material}
                  />
                  <points
                    name='mesh_89'
                    geometry={nodes.mesh_89.geometry}
                    material={nodes.mesh_89.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_19' userData={{ name: 'frame_19' }}>
                  <points
                    name='mesh_90'
                    geometry={nodes.mesh_90.geometry}
                    material={nodes.mesh_90.material}
                  />
                  <points
                    name='mesh_91'
                    geometry={nodes.mesh_91.geometry}
                    material={nodes.mesh_91.material}
                  />
                  <points
                    name='mesh_92'
                    geometry={nodes.mesh_92.geometry}
                    material={nodes.mesh_92.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_18' userData={{ name: 'frame_18' }}>
                  <points
                    name='mesh_93'
                    geometry={nodes.mesh_93.geometry}
                    material={nodes.mesh_93.material}
                  />
                  <points
                    name='mesh_94'
                    geometry={nodes.mesh_94.geometry}
                    material={nodes.mesh_94.material}
                  />
                  <points
                    name='mesh_95'
                    geometry={nodes.mesh_95.geometry}
                    material={nodes.mesh_95.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_17' userData={{ name: 'frame_17' }}>
                  <points
                    name='mesh_96'
                    geometry={nodes.mesh_96.geometry}
                    material={nodes.mesh_96.material}
                  />
                  <points
                    name='mesh_97'
                    geometry={nodes.mesh_97.geometry}
                    material={nodes.mesh_97.material}
                  />
                  <points
                    name='mesh_98'
                    geometry={nodes.mesh_98.geometry}
                    material={nodes.mesh_98.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_16' userData={{ name: 'frame_16' }}>
                  <points
                    name='mesh_99'
                    geometry={nodes.mesh_99.geometry}
                    material={nodes.mesh_99.material}
                  />
                  <points
                    name='mesh_100'
                    geometry={nodes.mesh_100.geometry}
                    material={nodes.mesh_100.material}
                  />
                  <points
                    name='mesh_101'
                    geometry={nodes.mesh_101.geometry}
                    material={nodes.mesh_101.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_15' userData={{ name: 'frame_15' }}>
                  <points
                    name='mesh_102'
                    geometry={nodes.mesh_102.geometry}
                    material={nodes.mesh_102.material}
                  />
                  <points
                    name='mesh_103'
                    geometry={nodes.mesh_103.geometry}
                    material={nodes.mesh_103.material}
                  />
                  <points
                    name='mesh_104'
                    geometry={nodes.mesh_104.geometry}
                    material={nodes.mesh_104.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_14' userData={{ name: 'frame_14' }}>
                  <points
                    name='mesh_105'
                    geometry={nodes.mesh_105.geometry}
                    material={nodes.mesh_105.material}
                  />
                  <points
                    name='mesh_106'
                    geometry={nodes.mesh_106.geometry}
                    material={nodes.mesh_106.material}
                  />
                  <points
                    name='mesh_107'
                    geometry={nodes.mesh_107.geometry}
                    material={nodes.mesh_107.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_13' userData={{ name: 'frame_13' }}>
                  <points
                    name='mesh_108'
                    geometry={nodes.mesh_108.geometry}
                    material={nodes.mesh_108.material}
                  />
                  <points
                    name='mesh_109'
                    geometry={nodes.mesh_109.geometry}
                    material={nodes.mesh_109.material}
                  />
                  <points
                    name='mesh_110'
                    geometry={nodes.mesh_110.geometry}
                    material={nodes.mesh_110.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_12' userData={{ name: 'frame_12' }}>
                  <points
                    name='mesh_111'
                    geometry={nodes.mesh_111.geometry}
                    material={nodes.mesh_111.material}
                  />
                  <points
                    name='mesh_112'
                    geometry={nodes.mesh_112.geometry}
                    material={nodes.mesh_112.material}
                  />
                  <points
                    name='mesh_113'
                    geometry={nodes.mesh_113.geometry}
                    material={nodes.mesh_113.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_11' userData={{ name: 'frame_11' }}>
                  <points
                    name='mesh_114'
                    geometry={nodes.mesh_114.geometry}
                    material={nodes.mesh_114.material}
                  />
                  <points
                    name='mesh_115'
                    geometry={nodes.mesh_115.geometry}
                    material={nodes.mesh_115.material}
                  />
                  <points
                    name='mesh_116'
                    geometry={nodes.mesh_116.geometry}
                    material={nodes.mesh_116.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_10' userData={{ name: 'frame_10' }}>
                  <points
                    name='mesh_117'
                    geometry={nodes.mesh_117.geometry}
                    material={nodes.mesh_117.material}
                  />
                  <points
                    name='mesh_118'
                    geometry={nodes.mesh_118.geometry}
                    material={nodes.mesh_118.material}
                  />
                  <points
                    name='mesh_119'
                    geometry={nodes.mesh_119.geometry}
                    material={nodes.mesh_119.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_9' userData={{ name: 'frame_9' }}>
                  <points
                    name='mesh_120'
                    geometry={nodes.mesh_120.geometry}
                    material={nodes.mesh_120.material}
                  />
                  <points
                    name='mesh_121'
                    geometry={nodes.mesh_121.geometry}
                    material={nodes.mesh_121.material}
                  />
                  <points
                    name='mesh_122'
                    geometry={nodes.mesh_122.geometry}
                    material={nodes.mesh_122.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_8' userData={{ name: 'frame_8' }}>
                  <points
                    name='mesh_123'
                    geometry={nodes.mesh_123.geometry}
                    material={nodes.mesh_123.material}
                  />
                  <points
                    name='mesh_124'
                    geometry={nodes.mesh_124.geometry}
                    material={nodes.mesh_124.material}
                  />
                  <points
                    name='mesh_125'
                    geometry={nodes.mesh_125.geometry}
                    material={nodes.mesh_125.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_7' userData={{ name: 'frame_7' }}>
                  <points
                    name='mesh_126'
                    geometry={nodes.mesh_126.geometry}
                    material={nodes.mesh_126.material}
                  />
                  <points
                    name='mesh_127'
                    geometry={nodes.mesh_127.geometry}
                    material={nodes.mesh_127.material}
                  />
                  <points
                    name='mesh_128'
                    geometry={nodes.mesh_128.geometry}
                    material={nodes.mesh_128.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_6' userData={{ name: 'frame_6' }}>
                  <points
                    name='mesh_129'
                    geometry={nodes.mesh_129.geometry}
                    material={nodes.mesh_129.material}
                  />
                  <points
                    name='mesh_130'
                    geometry={nodes.mesh_130.geometry}
                    material={nodes.mesh_130.material}
                  />
                  <points
                    name='mesh_131'
                    geometry={nodes.mesh_131.geometry}
                    material={nodes.mesh_131.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_5' userData={{ name: 'frame_5' }}>
                  <points
                    name='mesh_132'
                    geometry={nodes.mesh_132.geometry}
                    material={nodes.mesh_132.material}
                  />
                  <points
                    name='mesh_133'
                    geometry={nodes.mesh_133.geometry}
                    material={nodes.mesh_133.material}
                  />
                  <points
                    name='mesh_134'
                    geometry={nodes.mesh_134.geometry}
                    material={nodes.mesh_134.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_4' userData={{ name: 'frame_4' }}>
                  <points
                    name='mesh_135'
                    geometry={nodes.mesh_135.geometry}
                    material={nodes.mesh_135.material}
                  />
                  <points
                    name='mesh_136'
                    geometry={nodes.mesh_136.geometry}
                    material={nodes.mesh_136.material}
                  />
                  <points
                    name='mesh_137'
                    geometry={nodes.mesh_137.geometry}
                    material={nodes.mesh_137.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_3' userData={{ name: 'frame_3' }}>
                  <points
                    name='mesh_138'
                    geometry={nodes.mesh_138.geometry}
                    material={nodes.mesh_138.material}
                  />
                  <points
                    name='mesh_139'
                    geometry={nodes.mesh_139.geometry}
                    material={nodes.mesh_139.material}
                  />
                  <points
                    name='mesh_140'
                    geometry={nodes.mesh_140.geometry}
                    material={nodes.mesh_140.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_2' userData={{ name: 'frame_2' }}>
                  <points
                    name='mesh_141'
                    geometry={nodes.mesh_141.geometry}
                    material={nodes.mesh_141.material}
                  />
                  <points
                    name='mesh_142'
                    geometry={nodes.mesh_142.geometry}
                    material={nodes.mesh_142.material}
                  />
                  <points
                    name='mesh_143'
                    geometry={nodes.mesh_143.geometry}
                    material={nodes.mesh_143.material}
                  />
                </group>
              </group>
              <group scale={[0, 0, 0]}>
                <group name='frame_1' userData={{ name: 'frame_1' }}>
                  <points
                    name='mesh_144'
                    geometry={nodes.mesh_144.geometry}
                    material={nodes.mesh_144.material}
                  />
                  <points
                    name='mesh_145'
                    geometry={nodes.mesh_145.geometry}
                    material={nodes.mesh_145.material}
                  />
                  <points
                    name='mesh_146'
                    geometry={nodes.mesh_146.geometry}
                    material={nodes.mesh_146.material}
                  />
                </group>
              </group>
              <group>
                <group name='frame_0' userData={{ name: 'frame_0' }}>
                  <points
                    name='mesh_147'
                    geometry={nodes.mesh_147.geometry}
                    material={nodes.mesh_147.material}
                  />
                  <points
                    name='mesh_148'
                    geometry={nodes.mesh_148.geometry}
                    material={nodes.mesh_148.material}
                  />
                  <points
                    name='mesh_149'
                    geometry={nodes.mesh_149.geometry}
                    material={nodes.mesh_149.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/a_windy_day.gltf');
