/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DragonJojo (https://sketchfab.com/DragonJojo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/blue-glowing-butterfly-8fc026a9ee35463e96e38937a05a330b
title: Blue glowing butterfly
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/butterfly.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions.Anim_Merlin_PB?.play().setDuration(0.9);
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          position={[0.00451616, 1.99728405, -9.97679615]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: 'Sketchfab_model' }}
        >
          <group
            name='6cb9706577e44982a10dca33d66af2b7fbx'
            rotation={[-Math.PI, 0, 0]}
            scale={[0.01, 0.01, 0.01]}
            userData={{ name: '6cb9706577e44982a10dca33d66af2b7.fbx' }}
          >
            <group name='Object_2' userData={{ name: 'Object_2' }}>
              <group name='RootNode' userData={{ name: 'RootNode' }}>
                <group
                  name='PB_Corps'
                  position={[17.12376213, -500.96347046, -106.39080811]}
                  rotation={[-0.21574172, 0.51248449, 1.87680496]}
                  userData={{ name: 'PB_Corps' }}
                >
                  <group
                    name='PB_AileD'
                    rotation={[-1.22173104, -2.2e-7, -1.3962638]}
                    userData={{ name: 'PB_AileD' }}
                  >
                    <group
                      name='Object_8'
                      position={[0.34573179, 2.6e-7, -5.92741108]}
                      userData={{ name: 'Object_8' }}
                    >
                      <mesh
                        name='PB_AileD_Papillon_bleu_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.PB_AileD_Papillon_bleu_0.geometry}
                        material={nodes.PB_AileD_Papillon_bleu_0.material}
                        userData={{ name: 'PB_AileD_Papillon_bleu_0' }}
                      />
                    </group>
                  </group>
                  <group
                    name='PB_AileD001'
                    rotation={[-1.22173114, -2e-7, 1.39626369]}
                    userData={{ name: 'PB_AileD001' }}
                  >
                    <mesh
                      name='PB_AileD001_Papillon_bleu_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.PB_AileD001_Papillon_bleu_0.geometry}
                      material={nodes.PB_AileD001_Papillon_bleu_0.material}
                      userData={{ name: 'PB_AileD001_Papillon_bleu_0' }}
                    />
                  </group>
                  <group
                    name='Object_5'
                    position={[0, -3.54254079, -1.28937864]}
                    rotation={[-1.22173074, 0, 0]}
                    userData={{ name: 'Object_5' }}
                  >
                    <mesh
                      name='PB_Corps_Papillon_bleu_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.PB_Corps_Papillon_bleu_0.geometry}
                      material={nodes.PB_Corps_Papillon_bleu_0.material}
                      userData={{ name: 'PB_Corps_Papillon_bleu_0' }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/butterfly.gltf');
