/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/particles-cubed-6a3ef91e41914498b76585b21b7b2814
title: Particles Cubed
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/cube.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation?.play().setDuration(15);
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} scale={0.5}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.16248314, 0.16248314, 0.16248314]}
          userData={{ name: 'Sketchfab_model' }}
        >
          <group name='root' userData={{ name: 'root' }}>
            <group
              name='GLTF_SceneRootNode'
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: 'GLTF_SceneRootNode' }}
            >
              <group
                name='Sphere_0'
                position={[-4.14948845, -2.29003334, 2.13013792]}
                userData={{ name: 'Sphere_0' }}
              >
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={nodes.Object_4.material}
                  userData={{ name: 'Object_4' }}
                />
              </group>
              <group
                name='Sphere001_1'
                position={[-2.32765317, 3.31499624, 3.25466251]}
                userData={{ name: 'Sphere.001_1' }}
              >
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={nodes.Object_6.material}
                  userData={{ name: 'Object_6' }}
                />
              </group>
              <group
                name='Sphere002_2'
                position={[-1.50819671, 4.22700882, -2.61872816]}
                userData={{ name: 'Sphere.002_2' }}
              >
                <mesh
                  name='Object_8'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={nodes.Object_8.material}
                  userData={{ name: 'Object_8' }}
                />
              </group>
              <group
                name='Sphere003_3'
                position={[-3.33003211, -1.37802088, -3.74325275]}
                userData={{ name: 'Sphere.003_3' }}
              >
                <mesh
                  name='Object_10'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={nodes.Object_10.material}
                  userData={{ name: 'Object_10' }}
                />
              </group>
              <group
                name='Sphere004_4'
                position={[2.32765317, -3.31499624, -3.25466251]}
                userData={{ name: 'Sphere.004_4' }}
              >
                <mesh
                  name='Object_12'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={nodes.Object_12.material}
                  userData={{ name: 'Object_12' }}
                />
              </group>
              <group
                name='Sphere005_5'
                position={[4.14948845, 2.29003334, -2.13013792]}
                userData={{ name: 'Sphere.005_5' }}
              >
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={nodes.Object_14.material}
                  userData={{ name: 'Object_14' }}
                />
              </group>
              <group
                name='Sphere006_6'
                position={[2.24939895, -1.61337817, 4.39740992]}
                userData={{ name: 'Sphere.006_6' }}
              >
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={nodes.Object_16.material}
                  userData={{ name: 'Object_16' }}
                />
              </group>
              <group
                name='Sphere007_7'
                position={[4.11707497, 2.99486685, 1.03945446]}
                userData={{ name: 'Sphere.007_7' }}
              >
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={nodes.Object_18.material}
                  userData={{ name: 'Object_18' }}
                />
              </group>
              <group
                name='Sphere008_8'
                position={[-1.54061055, 4.93184233, 0.55086374]}
                userData={{ name: 'Sphere.008_8' }}
              >
                <mesh
                  name='Object_20'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={nodes.Object_20.material}
                  userData={{ name: 'Object_20' }}
                />
              </group>
              <group
                name='Sphere009_9'
                position={[-3.40828633, 0.32359731, 3.9088192]}
                userData={{ name: 'Sphere.009_9' }}
              >
                <mesh
                  name='Object_22'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={nodes.Object_22.material}
                  userData={{ name: 'Object_22' }}
                />
              </group>
              <group
                name='Sphere010_10'
                position={[-4.11707497, -2.99486685, -1.03945446]}
                userData={{ name: 'Sphere.010_10' }}
              >
                <mesh
                  name='Object_24'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={nodes.Object_24.material}
                  userData={{ name: 'Object_24' }}
                />
              </group>
              <group
                name='Sphere011_11'
                position={[-2.24939895, 1.61337817, -4.39740992]}
                userData={{ name: 'Sphere.011_11' }}
              >
                <mesh
                  name='Object_26'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={nodes.Object_26.material}
                  userData={{ name: 'Object_26' }}
                />
              </group>
              <group
                name='Sphere012_12'
                position={[-4.41031647, 0.91364193, 2.59120989]}
                userData={{ name: 'Sphere.012_12' }}
              >
                <mesh
                  name='Object_28'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={nodes.Object_28.material}
                  userData={{ name: 'Object_28' }}
                />
              </group>
              <group
                name='Sphere013_13'
                position={[0.87850356, 3.50734854, 3.73185444]}
                userData={{ name: 'Sphere.013_13' }}
              >
                <mesh
                  name='Object_30'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={nodes.Object_30.material}
                  userData={{ name: 'Object_30' }}
                />
              </group>
              <group
                name='Sphere014_14'
                position={[1.69796014, 4.41936111, -2.14153624]}
                userData={{ name: 'Sphere.014_14' }}
              >
                <mesh
                  name='Object_32'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={nodes.Object_32.material}
                  userData={{ name: 'Object_32' }}
                />
              </group>
              <group
                name='Sphere015_15'
                position={[-3.59085965, 1.82565451, -3.28218079]}
                userData={{ name: 'Sphere.015_15' }}
              >
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={nodes.Object_34.material}
                  userData={{ name: 'Object_34' }}
                />
              </group>
              <group
                name='Sphere016_16'
                position={[-0.87850356, -3.50734854, -3.73185444]}
                userData={{ name: 'Sphere.016_16' }}
              >
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={nodes.Object_36.material}
                  userData={{ name: 'Object_36' }}
                />
              </group>
              <group
                name='Sphere017_17'
                position={[4.41031647, -0.91364193, -2.59120989]}
                userData={{ name: 'Sphere.017_17' }}
              >
                <mesh
                  name='Object_38'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={nodes.Object_38.material}
                  userData={{ name: 'Object_38' }}
                />
              </group>
              <group
                name='Cube003_21'
                scale={[5.30000019, 5.30000019, 5.30000019]}
                userData={{ name: 'Cube.003_21' }}
              >
                <group
                  name='Cube_18'
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube_18' }}
                >
                  <mesh
                    name='Object_42'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={nodes.Object_42.material}
                    userData={{ name: 'Object_42' }}
                  />
                </group>
                <group
                  name='Cube001_19'
                  rotation={[-5e-8, Math.PI / 4, -Math.PI / 2]}
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube.001_19' }}
                >
                  <mesh
                    name='Object_44'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_44.geometry}
                    material={nodes.Object_44.material}
                    userData={{ name: 'Object_44' }}
                  />
                </group>
                <group
                  name='Cube002_20'
                  rotation={[-Math.PI / 4, 0, 0]}
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube.002_20' }}
                >
                  <mesh
                    name='Object_46'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={nodes.Object_46.material}
                    userData={{ name: 'Object_46' }}
                  />
                </group>
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={nodes.Object_40.material}
                  userData={{ name: 'Object_40' }}
                />
              </group>
              <group
                name='Sphere018_22'
                position={[3, 3, 3]}
                userData={{ name: 'Sphere.018_22' }}
              >
                <mesh
                  name='Object_48'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={nodes.Object_48.material}
                  userData={{ name: 'Object_48' }}
                />
              </group>
              <group
                name='Sphere019_23'
                position={[3, 3, -3]}
                userData={{ name: 'Sphere.019_23' }}
              >
                <mesh
                  name='Object_50'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={nodes.Object_50.material}
                  userData={{ name: 'Object_50' }}
                />
              </group>
              <group
                name='Sphere020_24'
                position={[-3, 3, -3]}
                userData={{ name: 'Sphere.020_24' }}
              >
                <mesh
                  name='Object_52'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={nodes.Object_52.material}
                  userData={{ name: 'Object_52' }}
                />
              </group>
              <group
                name='Sphere021_25'
                position={[-3, 3, 3]}
                userData={{ name: 'Sphere.021_25' }}
              >
                <mesh
                  name='Object_54'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={nodes.Object_54.material}
                  userData={{ name: 'Object_54' }}
                />
              </group>
              <group
                name='Sphere022_26'
                position={[-3, -3, 3]}
                userData={{ name: 'Sphere.022_26' }}
              >
                <mesh
                  name='Object_56'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={nodes.Object_56.material}
                  userData={{ name: 'Object_56' }}
                />
              </group>
              <group
                name='Sphere023_27'
                position={[-3, -3, -3]}
                userData={{ name: 'Sphere.023_27' }}
              >
                <mesh
                  name='Object_58'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={nodes.Object_58.material}
                  userData={{ name: 'Object_58' }}
                />
              </group>
              <group
                name='Sphere024_28'
                position={[4.24264097, -2.99999952, 0]}
                userData={{ name: 'Sphere.024_28' }}
              >
                <mesh
                  name='Object_60'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={nodes.Object_60.material}
                  userData={{ name: 'Object_60' }}
                />
              </group>
              <group
                name='Sphere025_29'
                position={[0, -3, -4.2426405]}
                userData={{ name: 'Sphere.025_29' }}
              >
                <mesh
                  name='Object_62'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={nodes.Object_62.material}
                  userData={{ name: 'Object_62' }}
                />
              </group>
              <group
                name='Sphere026_30'
                position={[0, 3, -4.2426405]}
                userData={{ name: 'Sphere.026_30' }}
              >
                <mesh
                  name='Object_64'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={nodes.Object_64.material}
                  userData={{ name: 'Object_64' }}
                />
              </group>
              <group
                name='Sphere027_31'
                position={[4.2426405, 3.00000048, 0]}
                userData={{ name: 'Sphere.027_31' }}
              >
                <mesh
                  name='Object_66'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={nodes.Object_66.material}
                  userData={{ name: 'Object_66' }}
                />
              </group>
              <group
                name='Sphere028_32'
                position={[0, 3, 4.2426405]}
                userData={{ name: 'Sphere.028_32' }}
              >
                <mesh
                  name='Object_68'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={nodes.Object_68.material}
                  userData={{ name: 'Object_68' }}
                />
              </group>
              <group
                name='Sphere029_33'
                position={[-4.24264097, 2.99999952, 0]}
                userData={{ name: 'Sphere.029_33' }}
              >
                <mesh
                  name='Object_70'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={nodes.Object_70.material}
                  userData={{ name: 'Object_70' }}
                />
              </group>
              <group
                name='Sphere030_34'
                position={[3, 4.2426405, 0]}
                userData={{ name: 'Sphere.030_34' }}
              >
                <mesh
                  name='Object_72'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={nodes.Object_72.material}
                  userData={{ name: 'Object_72' }}
                />
              </group>
              <group
                name='Sphere031_35'
                position={[3, 0, -4.2426405]}
                userData={{ name: 'Sphere.031_35' }}
              >
                <mesh
                  name='Object_74'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={nodes.Object_74.material}
                  userData={{ name: 'Object_74' }}
                />
              </group>
              <group
                name='Sphere032_36'
                position={[-3, 0, -4.2426405]}
                userData={{ name: 'Sphere.032_36' }}
              >
                <mesh
                  name='Object_76'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={nodes.Object_76.material}
                  userData={{ name: 'Object_76' }}
                />
              </group>
              <group
                name='Sphere033_37'
                position={[-3, 4.2426405, 0]}
                userData={{ name: 'Sphere.033_37' }}
              >
                <mesh
                  name='Object_78'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={nodes.Object_78.material}
                  userData={{ name: 'Object_78' }}
                />
              </group>
              <group
                name='Sphere034_38'
                position={[-3, 0, 4.2426405]}
                userData={{ name: 'Sphere.034_38' }}
              >
                <mesh
                  name='Object_80'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={nodes.Object_80.material}
                  userData={{ name: 'Object_80' }}
                />
              </group>
              <group
                name='Sphere035_39'
                position={[-3, -4.2426405, 0]}
                userData={{ name: 'Sphere.035_39' }}
              >
                <mesh
                  name='Object_82'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={nodes.Object_82.material}
                  userData={{ name: 'Object_82' }}
                />
              </group>
              <group
                name='Cube007_43'
                scale={[5.30000019, 5.30000019, 5.30000019]}
                userData={{ name: 'Cube.007_43' }}
              >
                <group
                  name='Cube004_40'
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube.004_40' }}
                >
                  <mesh
                    name='Object_86'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_86.geometry}
                    material={nodes.Object_86.material}
                    userData={{ name: 'Object_86' }}
                  />
                </group>
                <group
                  name='Cube005_41'
                  rotation={[-5e-8, Math.PI / 4, -Math.PI / 2]}
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube.005_41' }}
                >
                  <mesh
                    name='Object_88'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_88.geometry}
                    material={nodes.Object_88.material}
                    userData={{ name: 'Object_88' }}
                  />
                </group>
                <group
                  name='Cube006_42'
                  rotation={[-Math.PI / 4, 0, 0]}
                  scale={[0.56603771, 0.56603771, 0.56603771]}
                  userData={{ name: 'Cube.006_42' }}
                >
                  <mesh
                    name='Object_90'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_90.geometry}
                    material={nodes.Object_90.material}
                    userData={{ name: 'Object_90' }}
                  />
                </group>
                <mesh
                  name='Object_84'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={nodes.Object_84.material}
                  userData={{ name: 'Object_84' }}
                />
              </group>
              <group
                name='Sphere036_45'
                position={[-4.14948845, -2.29003334, 2.13013792]}
                userData={{ name: 'Sphere.036_45' }}
              >
                <mesh
                  name='Object_94'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={nodes.Object_94.material}
                  userData={{ name: 'Object_94' }}
                />
              </group>
              <group
                name='Sphere037_46'
                position={[-2.32765317, 3.31499624, 3.25466251]}
                userData={{ name: 'Sphere.037_46' }}
              >
                <mesh
                  name='Object_96'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={nodes.Object_96.material}
                  userData={{ name: 'Object_96' }}
                />
              </group>
              <group
                name='Sphere038_47'
                position={[-1.50819671, 4.22700882, -2.61872816]}
                userData={{ name: 'Sphere.038_47' }}
              >
                <mesh
                  name='Object_98'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={nodes.Object_98.material}
                  userData={{ name: 'Object_98' }}
                />
              </group>
              <group
                name='Sphere039_48'
                position={[-3.33003211, -1.37802088, -3.74325275]}
                userData={{ name: 'Sphere.039_48' }}
              >
                <mesh
                  name='Object_100'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={nodes.Object_100.material}
                  userData={{ name: 'Object_100' }}
                />
              </group>
              <group
                name='Sphere040_49'
                position={[2.32765317, -3.31499624, -3.25466251]}
                userData={{ name: 'Sphere.040_49' }}
              >
                <mesh
                  name='Object_102'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={nodes.Object_102.material}
                  userData={{ name: 'Object_102' }}
                />
              </group>
              <group
                name='Sphere041_50'
                position={[4.14948845, 2.29003334, -2.13013792]}
                userData={{ name: 'Sphere.041_50' }}
              >
                <mesh
                  name='Object_104'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={nodes.Object_104.material}
                  userData={{ name: 'Object_104' }}
                />
              </group>
              <group
                name='Sphere042_51'
                position={[2.24939895, -1.61337817, 4.39740992]}
                userData={{ name: 'Sphere.042_51' }}
              >
                <mesh
                  name='Object_106'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={nodes.Object_106.material}
                  userData={{ name: 'Object_106' }}
                />
              </group>
              <group
                name='Sphere043_52'
                position={[4.11707497, 2.99486685, 1.03945446]}
                userData={{ name: 'Sphere.043_52' }}
              >
                <mesh
                  name='Object_108'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={nodes.Object_108.material}
                  userData={{ name: 'Object_108' }}
                />
              </group>
              <group
                name='Sphere044_53'
                position={[-1.54061055, 4.93184233, 0.55086374]}
                userData={{ name: 'Sphere.044_53' }}
              >
                <mesh
                  name='Object_110'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={nodes.Object_110.material}
                  userData={{ name: 'Object_110' }}
                />
              </group>
              <group
                name='Sphere045_54'
                position={[-3.40828633, 0.32359731, 3.9088192]}
                userData={{ name: 'Sphere.045_54' }}
              >
                <mesh
                  name='Object_112'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={nodes.Object_112.material}
                  userData={{ name: 'Object_112' }}
                />
              </group>
              <group
                name='Sphere046_55'
                position={[-4.11707497, -2.99486685, -1.03945446]}
                userData={{ name: 'Sphere.046_55' }}
              >
                <mesh
                  name='Object_114'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={nodes.Object_114.material}
                  userData={{ name: 'Object_114' }}
                />
              </group>
              <group
                name='Sphere047_56'
                position={[-2.24939895, 1.61337817, -4.39740992]}
                userData={{ name: 'Sphere.047_56' }}
              >
                <mesh
                  name='Object_116'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={nodes.Object_116.material}
                  userData={{ name: 'Object_116' }}
                />
              </group>
              <group
                name='Sphere048_57'
                position={[-4.41031647, 0.91364193, 2.59120989]}
                userData={{ name: 'Sphere.048_57' }}
              >
                <mesh
                  name='Object_118'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={nodes.Object_118.material}
                  userData={{ name: 'Object_118' }}
                />
              </group>
              <group
                name='Sphere049_58'
                position={[0.87850356, 3.50734854, 3.73185444]}
                userData={{ name: 'Sphere.049_58' }}
              >
                <mesh
                  name='Object_120'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={nodes.Object_120.material}
                  userData={{ name: 'Object_120' }}
                />
              </group>
              <group
                name='Sphere050_59'
                position={[1.69796014, 4.41936111, -2.14153624]}
                userData={{ name: 'Sphere.050_59' }}
              >
                <mesh
                  name='Object_122'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={nodes.Object_122.material}
                  userData={{ name: 'Object_122' }}
                />
              </group>
              <group
                name='Sphere051_60'
                position={[-3.59085965, 1.82565451, -3.28218079]}
                userData={{ name: 'Sphere.051_60' }}
              >
                <mesh
                  name='Object_124'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={nodes.Object_124.material}
                  userData={{ name: 'Object_124' }}
                />
              </group>
              <group
                name='Sphere052_61'
                position={[-0.87850356, -3.50734854, -3.73185444]}
                userData={{ name: 'Sphere.052_61' }}
              >
                <mesh
                  name='Object_126'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={nodes.Object_126.material}
                  userData={{ name: 'Object_126' }}
                />
              </group>
              <group
                name='Sphere053_62'
                position={[4.41031647, -0.91364193, -2.59120989]}
                userData={{ name: 'Sphere.053_62' }}
              >
                <mesh
                  name='Object_128'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={nodes.Object_128.material}
                  userData={{ name: 'Object_128' }}
                />
              </group>
              <group
                name='Sphere054_63'
                position={[3, 3, 3]}
                userData={{ name: 'Sphere.054_63' }}
              >
                <mesh
                  name='Object_130'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={nodes.Object_130.material}
                  userData={{ name: 'Object_130' }}
                />
              </group>
              <group
                name='Sphere055_64'
                position={[3, 3, -3]}
                userData={{ name: 'Sphere.055_64' }}
              >
                <mesh
                  name='Object_132'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_132.geometry}
                  material={nodes.Object_132.material}
                  userData={{ name: 'Object_132' }}
                />
              </group>
              <group
                name='Sphere056_65'
                position={[-3, 3, -3]}
                userData={{ name: 'Sphere.056_65' }}
              >
                <mesh
                  name='Object_134'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={nodes.Object_134.material}
                  userData={{ name: 'Object_134' }}
                />
              </group>
              <group
                name='Sphere057_66'
                position={[-3, 3, 3]}
                userData={{ name: 'Sphere.057_66' }}
              >
                <mesh
                  name='Object_136'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={nodes.Object_136.material}
                  userData={{ name: 'Object_136' }}
                />
              </group>
              <group
                name='Sphere058_67'
                position={[-3, -3, 3]}
                userData={{ name: 'Sphere.058_67' }}
              >
                <mesh
                  name='Object_138'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={nodes.Object_138.material}
                  userData={{ name: 'Object_138' }}
                />
              </group>
              <group
                name='Sphere059_68'
                position={[-3, -3, -3]}
                userData={{ name: 'Sphere.059_68' }}
              >
                <mesh
                  name='Object_140'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_140.geometry}
                  material={nodes.Object_140.material}
                  userData={{ name: 'Object_140' }}
                />
              </group>
              <group
                name='Sphere060_69'
                position={[4.24264097, -2.99999952, 0]}
                userData={{ name: 'Sphere.060_69' }}
              >
                <mesh
                  name='Object_142'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={nodes.Object_142.material}
                  userData={{ name: 'Object_142' }}
                />
              </group>
              <group
                name='Sphere061_70'
                position={[0, -3, -4.2426405]}
                userData={{ name: 'Sphere.061_70' }}
              >
                <mesh
                  name='Object_144'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={nodes.Object_144.material}
                  userData={{ name: 'Object_144' }}
                />
              </group>
              <group
                name='Sphere062_71'
                position={[0, 3, -4.2426405]}
                userData={{ name: 'Sphere.062_71' }}
              >
                <mesh
                  name='Object_146'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={nodes.Object_146.material}
                  userData={{ name: 'Object_146' }}
                />
              </group>
              <group
                name='Sphere063_72'
                position={[4.2426405, 3.00000048, 0]}
                userData={{ name: 'Sphere.063_72' }}
              >
                <mesh
                  name='Object_148'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={nodes.Object_148.material}
                  userData={{ name: 'Object_148' }}
                />
              </group>
              <group
                name='Sphere064_73'
                position={[0, 3, 4.2426405]}
                userData={{ name: 'Sphere.064_73' }}
              >
                <mesh
                  name='Object_150'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_150.geometry}
                  material={nodes.Object_150.material}
                  userData={{ name: 'Object_150' }}
                />
              </group>
              <group
                name='Sphere065_74'
                position={[-4.24264097, 2.99999952, 0]}
                userData={{ name: 'Sphere.065_74' }}
              >
                <mesh
                  name='Object_152'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_152.geometry}
                  material={nodes.Object_152.material}
                  userData={{ name: 'Object_152' }}
                />
              </group>
              <group
                name='Sphere066_75'
                position={[3, 4.2426405, 0]}
                userData={{ name: 'Sphere.066_75' }}
              >
                <mesh
                  name='Object_154'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={nodes.Object_154.material}
                  userData={{ name: 'Object_154' }}
                />
              </group>
              <group
                name='Sphere067_76'
                position={[3, 0, -4.2426405]}
                userData={{ name: 'Sphere.067_76' }}
              >
                <mesh
                  name='Object_156'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={nodes.Object_156.material}
                  userData={{ name: 'Object_156' }}
                />
              </group>
              <group
                name='Sphere068_77'
                position={[-3, 0, -4.2426405]}
                userData={{ name: 'Sphere.068_77' }}
              >
                <mesh
                  name='Object_158'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_158.geometry}
                  material={nodes.Object_158.material}
                  userData={{ name: 'Object_158' }}
                />
              </group>
              <group
                name='Sphere069_78'
                position={[-3, 4.2426405, 0]}
                userData={{ name: 'Sphere.069_78' }}
              >
                <mesh
                  name='Object_160'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_160.geometry}
                  material={nodes.Object_160.material}
                  userData={{ name: 'Object_160' }}
                />
              </group>
              <group
                name='Sphere070_79'
                position={[-3, 0, 4.2426405]}
                userData={{ name: 'Sphere.070_79' }}
              >
                <mesh
                  name='Object_162'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_162.geometry}
                  material={nodes.Object_162.material}
                  userData={{ name: 'Object_162' }}
                />
              </group>
              <group
                name='Sphere071_80'
                position={[-3, -4.2426405, 0]}
                userData={{ name: 'Sphere.071_80' }}
              >
                <mesh
                  name='Object_164'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_164.geometry}
                  material={nodes.Object_164.material}
                  userData={{ name: 'Object_164' }}
                />
              </group>
              <group
                name='Cube008_44'
                rotation={[1.7687954, -0.30850989, 1.71463557]}
                scale={[1, 1, 1]}
                userData={{ name: 'Cube.008_44' }}
              >
                <mesh
                  name='Object_92'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={nodes.Object_92.material}
                  userData={{ name: 'Object_92' }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/cube.gltf');
