/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Josh Johanson (https://sketchfab.com/johansome)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0609b2daeab3477497ef52cca3b6801c
title: Medium - Cute Robo-Drone
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/cute_robot.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.25, 0.34]} rotation={[-Math.PI, 0, 0]}>
          <group rotation={[-Math.PI, 0, 0]}>
            <mesh
              geometry={nodes.body__0.geometry}
              material={nodes.body__0.material}
            />
            <mesh
              geometry={nodes.rockets__0.geometry}
              material={nodes.rockets__0.material}
            />
            <mesh
              geometry={nodes.fins__0.geometry}
              material={nodes.fins__0.material}
            />
            <mesh
              geometry={nodes.faceplate__0.geometry}
              material={nodes.faceplate__0.material}
            />
            <mesh
              geometry={nodes.head__0.geometry}
              material={nodes.head__0.material}
            />
            <mesh
              geometry={nodes.head__0_1.geometry}
              material={nodes.head__0_1.material}
            />
            <mesh
              geometry={nodes.emiss__0.geometry}
              material={nodes.emiss__0.material}
            />
            <mesh
              geometry={nodes.Lhnd__0.geometry}
              material={nodes.Lhnd__0.material}
            />
            <mesh
              geometry={nodes.Rhnd__0.geometry}
              material={nodes.Rhnd__0.material}
            />
            <mesh
              geometry={nodes.wre__0.geometry}
              material={nodes.wre__0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/cute_robot.gltf');
