/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Renafox (https://sketchfab.com/kryik1023)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/models/ce248709dea64ec1844e8dd9b614f7c0
title: Drone
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/drone.gltf');
  return (
    <group ref={group} {...props} dispose={null} scale={0.05}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 2.05, 0]}>
          <group position={[0, 63.8, 0.37]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              geometry={nodes['Box001_Material_#4_0'].geometry}
              material={materials.Material_4}
            />
          </group>
          <group position={[0, 63.8, 0.37]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              geometry={nodes['Object002_Material_#5_0'].geometry}
              material={materials.Material_5}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/drone.gltf');
