/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: msanjurj (https://sketchfab.com/msanjurj)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hologram-ef9120160bcc482b9be1d723cffa89d2
title: HOLOGRAM
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/holo.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions.Holo_03?.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.28, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
            <group position={[-635.17, -0.52, 0]}>
              <group position={[41.04, 0, 0]}>
                <mesh
                  geometry={nodes['Shape002_Material_#25_0'].geometry}
                  material={nodes['Shape002_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, 566.44, 0]}>
              <group position={[0, -41.04, 0]}>
                <mesh
                  geometry={nodes['Shape001_Material_#25_0'].geometry}
                  material={nodes['Shape001_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, 511.88, 30.65]}>
              <group position={[0, -41.04, -30.65]}>
                <mesh
                  geometry={nodes['Shape007_Material_#25_0'].geometry}
                  material={nodes['Shape007_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, -1127.57, 30.65]}>
              <group position={[0, 41.04, -30.65]}>
                <mesh
                  geometry={nodes['Shape006_Material_#25_0'].geometry}
                  material={nodes['Shape006_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[2880.97, -0.52, 0]}>
              <group position={[-41.04, 0, 0]}>
                <mesh
                  geometry={nodes['Shape008_Material_#25_0'].geometry}
                  material={nodes['Shape008_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-359.44, 373.19, 15.32]}>
              <group position={[41.04, -41.04, -15.32]}>
                <mesh
                  geometry={nodes['Shape003_Material_#25_0'].geometry}
                  material={nodes['Shape003_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, -737.21, 0]}>
              <group position={[0, 41.04, 0]}>
                <mesh
                  geometry={nodes['Shape005_Material_#25_0'].geometry}
                  material={nodes['Shape005_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-964.12, -0.52, 30.65]}>
              <group position={[41.04, 0, -30.65]}>
                <mesh
                  geometry={nodes['Shape009_Material_#25_0'].geometry}
                  material={nodes['Shape009_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[882.01, -905.53, 15.32]}>
              <group position={[-41.04, 41.04, -15.32]}>
                <mesh
                  geometry={nodes['Shape010_Material_#25_0'].geometry}
                  material={nodes['Shape010_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[697.08, -0.52, 30.65]}>
              <group position={[-41.04, 0, -30.65]}>
                <mesh
                  geometry={nodes['Shape004_Material_#25_0'].geometry}
                  material={nodes['Shape004_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-964.12, -0.52, 30.65]}>
              <group position={[41.04, 0, -30.65]}>
                <mesh
                  geometry={nodes['Shape015_Material_#25_0'].geometry}
                  material={nodes['Shape015_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, -737.21, 0]}>
              <group position={[0, 41.04, 0]}>
                <mesh
                  geometry={nodes['Shape016_Material_#25_0'].geometry}
                  material={nodes['Shape016_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, -1127.57, 30.65]}>
              <group position={[0, 41.04, -30.65]}>
                <mesh
                  geometry={nodes['Shape017_Material_#25_0'].geometry}
                  material={nodes['Shape017_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[2880.97, -0.52, 0]}>
              <group position={[-41.04, 0, 0]}>
                <mesh
                  geometry={nodes['Shape018_Material_#25_0'].geometry}
                  material={nodes['Shape018_Material_#25_0'].material}
                />
              </group>
            </group>
            <group position={[-0.52, 566.44, 0]}>
              <group position={[0, -41.04, 0]}>
                <mesh
                  geometry={nodes['Shape019_Material_#25_0'].geometry}
                  material={nodes['Shape019_Material_#25_0'].material}
                />
              </group>
            </group>
          </group>
          <group
            position={[-0.36, 0.13, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['4_Material_#25_0'].geometry}
              material={nodes['4_Material_#25_0'].material}
            />
          </group>
          <group
            position={[-0.36, -0.3, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['2_Material_#25_0'].geometry}
              material={nodes['2_Material_#25_0'].material}
            />
          </group>
          <group
            name='3'
            position={[-0.36, -0.29, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['3_Material_#25_0'].geometry}
              material={nodes['3_Material_#25_0'].material}
            />
          </group>
          <group
            position={[-0.36, -0.08, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <mesh
              geometry={nodes['1_Material_#25_0'].geometry}
              material={nodes['1_Material_#25_0'].material}
            />
          </group>
          <group
            position={[-0.36, -0.08, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <mesh
              geometry={nodes['005_Material_#25_0'].geometry}
              material={nodes['005_Material_#25_0'].material}
            />
          </group>
          <group
            position={[-0.36, 0.13, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['006_Material_#25_0'].geometry}
              material={nodes['006_Material_#25_0'].material}
            />
          </group>
          <group
            position={[-0.36, -0.29, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['007_Material_#25_0'].geometry}
              material={nodes['007_Material_#25_0'].material}
            />
          </group>
          <group
            name='008'
            position={[-0.36, -0.3, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes['008_Material_#25_0'].geometry}
              material={nodes['008_Material_#25_0'].material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/holo.gltf');
