/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Elin (https://sketchfab.com/ElinHohler)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/matrix-void-abbe6f13ce8f477999fb0501476658bf
title: Matrix Void
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/matrix.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'Sketchfab_model' }}
        >
          <group name='root' userData={{ name: 'root' }}>
            <group
              name='GLTF_SceneRootNode'
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: 'GLTF_SceneRootNode' }}
            >
              <group
                name='color003_19'
                position={[-1.8825053, 5.15079308, -0.86702657]}
                userData={{ name: 'color.003_19' }}
              >
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={nodes.Object_4.material}
                  userData={{ name: 'Object_4' }}
                />
              </group>
              <group
                name='color004_20'
                position={[0.83078229, 3.32091141, 1.61165333]}
                userData={{ name: 'color.004_20' }}
              >
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={nodes.Object_6.material}
                  userData={{ name: 'Object_6' }}
                />
              </group>
              <group
                name='color011_21'
                position={[1.07532024, 5.15079308, -2.48505712]}
                userData={{ name: 'color.011_21' }}
              >
                <mesh
                  name='Object_8'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={nodes.Object_8.material}
                  userData={{ name: 'Object_8' }}
                />
              </group>
              <group
                name='color012_22'
                position={[1.58123887, 3.32091141, -0.23013783]}
                userData={{ name: 'color.012_22' }}
              >
                <mesh
                  name='Object_10'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={nodes.Object_10.material}
                  userData={{ name: 'Object_10' }}
                />
              </group>
              <group
                name='color013_23'
                position={[-1.23661625, 3.32091141, -2.58926392]}
                userData={{ name: 'color.013_23' }}
              >
                <mesh
                  name='Object_12'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={nodes.Object_12.material}
                  userData={{ name: 'Object_12' }}
                />
              </group>
              <group
                name='color017_24'
                position={[2.04947996, 3.32091141, 2.09787941]}
                userData={{ name: 'color.017_24' }}
              >
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={nodes.Object_14.material}
                  userData={{ name: 'Object_14' }}
                />
              </group>
              <group
                name='color021_25'
                position={[-0.06998193, 3.32091141, 1.2479918]}
                userData={{ name: 'color.021_25' }}
              >
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={nodes.Object_16.material}
                  userData={{ name: 'Object_16' }}
                />
              </group>
              <group
                name='color029_26'
                position={[0.87336946, 6.53091908, 2.49677229]}
                scale={[1.9474169, 1.94741678, 1.9474169]}
                userData={{ name: 'color.029_26' }}
              >
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={nodes.Object_18.material}
                  userData={{ name: 'Object_18' }}
                />
              </group>
              <group
                name='color030_27'
                position={[-1.95355284, 4.56187868, 1.09045506]}
                scale={[1.36626482, 1.36626482, 1.36626482]}
                userData={{ name: 'color.030_27' }}
              >
                <mesh
                  name='Object_20'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={nodes.Object_20.material}
                  userData={{ name: 'Object_20' }}
                />
              </group>
              <group
                name='color031_28'
                position={[2.97576618, 4.56187868, 0.1350584]}
                scale={[1.36626494, 1.36626482, 1.36626494]}
                userData={{ name: 'color.031_28' }}
              >
                <mesh
                  name='Object_22'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={nodes.Object_22.material}
                  userData={{ name: 'Object_22' }}
                />
              </group>
              <group
                name='color032_29'
                position={[0.15518208, 4.56187868, -4.27041817]}
                scale={[1.36626494, 1.36626482, 1.36626494]}
                userData={{ name: 'color.032_29' }}
              >
                <mesh
                  name='Object_24'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={nodes.Object_24.material}
                  userData={{ name: 'Object_24' }}
                />
              </group>
              <group
                name='color033_30'
                position={[-2.96458006, 4.56187868, 4.43686676]}
                scale={[1.36626494, 1.36626482, 1.36626494]}
                userData={{ name: 'color.033_30' }}
              >
                <mesh
                  name='Object_26'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={nodes.Object_26.material}
                  userData={{ name: 'Object_26' }}
                />
              </group>
              <group
                name='color037_31'
                position={[2.47992134, 8.47132778, -1.09034348]}
                scale={[2.52011824, 2.520118, 2.52011824]}
                userData={{ name: 'color.037_31' }}
              >
                <mesh
                  name='Object_28'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={nodes.Object_28.material}
                  userData={{ name: 'Object_28' }}
                />
              </group>
              <group
                name='color038_32'
                position={[-3.24926329, 10.30120945, -1.99137259]}
                scale={[2.52011824, 2.520118, 2.52011824]}
                userData={{ name: 'color.038_32' }}
              >
                <mesh
                  name='Object_30'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={nodes.Object_30.material}
                  userData={{ name: 'Object_30' }}
                />
              </group>
              <group
                name='color039_33'
                position={[-3.84428239, 8.47132778, 1.66374516]}
                scale={[2.52011824, 2.520118, 2.52011824]}
                userData={{ name: 'color.039_33' }}
              >
                <mesh
                  name='Object_32'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={nodes.Object_32.material}
                  userData={{ name: 'Object_32' }}
                />
              </group>
              <group
                name='color040_34'
                position={[-2.4162364, 8.47132778, -0.10431182]}
                scale={[2.52011824, 2.520118, 2.52011824]}
                userData={{ name: 'color.040_34' }}
              >
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={nodes.Object_34.material}
                  userData={{ name: 'Object_34' }}
                />
              </group>
              <group
                name='color041_35'
                position={[4.47748566, 8.47132683, 1.6127435]}
                scale={[2.52011824, 2.520118, 2.52011824]}
                userData={{ name: 'color.041_35' }}
              >
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={nodes.Object_36.material}
                  userData={{ name: 'Object_36' }}
                />
              </group>
              <group
                name='color042_36'
                position={[4.06097221, 11.67162323, -2.83290005]}
                scale={[3.46466875, 3.46466827, 3.46466875]}
                userData={{ name: 'color.042_36' }}
              >
                <mesh
                  name='Object_38'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={nodes.Object_38.material}
                  userData={{ name: 'Object_38' }}
                />
              </group>
              <group
                name='color043_37'
                position={[-1.63081062, 11.67162323, -4.47311306]}
                scale={[3.46466875, 3.46466827, 3.46466875]}
                userData={{ name: 'color.043_37' }}
              >
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={nodes.Object_40.material}
                  userData={{ name: 'Object_40' }}
                />
              </group>
              <group
                name='Circle002_47'
                position={[0, -0.02178424, -0.0608128]}
                scale={[2.13618231, 2.13618231, 2.13618231]}
                userData={{ name: 'Circle.002_47' }}
              >
                <mesh
                  name='Object_61'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={nodes.Object_61.material}
                  userData={{ name: 'Object_61' }}
                />
              </group>
              <group
                name='Cylinder001_49'
                position={[0, -64.01825714, 0]}
                scale={[0.0711314, 0.0711314, 0.0711314]}
                userData={{ name: 'Cylinder.001_49' }}
              >
                <mesh
                  name='Object_65'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={nodes.Object_65.material}
                  userData={{ name: 'Object_65' }}
                />
              </group>
              <group
                name='mask003_38'
                position={[-1.87591612, 0.87445545, -0.86450571]}
                rotation={[0, 1.20539977, 0]}
                userData={{ name: 'mask.003_38' }}
              >
                <mesh
                  name='Object_42'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={nodes.Object_42.material}
                  userData={{ name: 'Object_42' }}
                />
              </group>
              <group
                name='CatMesh2_39'
                position={[1.7634809, 0, -1.30373907]}
                rotation={[Math.PI / 2, 1e-7, 0.68839775]}
                scale={[0.05144551, 0.05144551, 0.0514455]}
                userData={{ name: 'CatMesh2_39' }}
              >
                <mesh
                  name='Object_45'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={nodes.Object_45.material}
                  userData={{ name: 'Object_45' }}
                />
                <mesh
                  name='Object_44'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={nodes.Object_44.material}
                  userData={{ name: 'Object_44' }}
                />
              </group>
              <group
                name='CatMesh2001_40'
                position={[1.7634809, 0, -1.30373907]}
                rotation={[Math.PI / 2, 1e-7, 0.68839775]}
                scale={[0.05144551, 0.05144551, 0.0514455]}
                userData={{ name: 'CatMesh2.001_40' }}
              >
                <mesh
                  name='Object_47'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={nodes.Object_47.material}
                  userData={{ name: 'Object_47' }}
                />
              </group>
              <group
                name='Plane026_41'
                position={[1.74260104, 0, -1.37237847]}
                rotation={[-Math.PI, 0.80906382, -Math.PI]}
                scale={[0.04213045, 0.04213045, 0.04213045]}
                userData={{ name: 'Plane.026_41' }}
              >
                <mesh
                  name='Object_49'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.material}
                  userData={{ name: 'Object_49' }}
                />
              </group>
              <group
                name='man_in_suit002_42'
                position={[-1.76543927, 0, 1.73156214]}
                rotation={[Math.PI / 2, -1.1e-7, -2.50011225]}
                userData={{ name: 'man_in_suit.002_42' }}
              >
                <mesh
                  name='Object_51'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={nodes.Object_51.material}
                  userData={{ name: 'Object_51' }}
                />
              </group>
              <group
                name='man_in_suit001_43'
                position={[-1.76543927, 0, 1.73156214]}
                rotation={[Math.PI / 2, -1.1e-7, -2.50011225]}
                userData={{ name: 'man_in_suit.001_43' }}
              >
                <mesh
                  name='Object_53'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={nodes.Object_53.material}
                  userData={{ name: 'Object_53' }}
                />
              </group>
              <group
                name='Korpus_44'
                position={[-1.13883948, 1.47389174, 1.4236114]}
                rotation={[1.55452262, 0.00249437, -0.82103872]}
                scale={[0.00143751, 0.00143751, 0.00143751]}
                userData={{ name: 'Korpus_44' }}
              >
                <mesh
                  name='Object_55'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={nodes.Object_55.material}
                  userData={{ name: 'Object_55' }}
                />
              </group>
              <group
                name='Circle_45'
                scale={[2.13618231, 2.13618231, 2.13618231]}
                userData={{ name: 'Circle_45' }}
              >
                <mesh
                  name='Object_57'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_57.geometry}
                  material={nodes.Object_57.material}
                  userData={{ name: 'Object_57' }}
                />
              </group>
              <group
                name='Circle001_46'
                position={[0, -0.01159499, 0]}
                scale={[2.13618231, 2.13618231, 2.13618231]}
                userData={{ name: 'Circle.001_46' }}
              >
                <mesh
                  name='Object_59'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={nodes.Object_59.material}
                  userData={{ name: 'Object_59' }}
                />
              </group>
              <group
                name='Korpus001_48'
                position={[-1.13883948, 1.47389174, 1.4236114]}
                rotation={[1.55452262, 0.00249437, -0.82103872]}
                scale={[0.00143751, 0.00143751, 0.00143751]}
                userData={{ name: 'Korpus.001_48' }}
              >
                <mesh
                  name='Object_63'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={nodes.Object_63.material}
                  userData={{ name: 'Object_63' }}
                />
              </group>
              <group
                name='Empty_51'
                scale={[0.0711314, 0.0711314, 0.0711314]}
                userData={{ name: 'Empty_51' }}
              >
                <group
                  name='Cylinder_50'
                  position={[0, 98.30950928, 0]}
                  userData={{ name: 'Cylinder_50' }}
                >
                  <mesh
                    name='Object_68'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={nodes.Object_68.material}
                    userData={{ name: 'Object_68' }}
                  />
                </group>
              </group>
              <group
                name='Plane_52'
                position={[0, 19.24390221, 0]}
                scale={[8.9420023, 8.9420023, 8.9420023]}
                userData={{ name: 'Plane_52' }}
              >
                <mesh
                  name='Object_70'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.Alpha}
                  userData={{ name: 'Object_70' }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/matrix.gltf');
