/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MvdE (https://sketchfab.com/MvdE)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-head-e869717813844a06ab340feb893a81aa
title: Low-poly Head
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/poly_head.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='OSG_Scene'>
        <group
          name='RootNode_(gltf_orientation_matrix)'
          rotation={[-Math.PI / 2, 0, 3.6]}
          userData={{ name: 'RootNode (gltf orientation matrix)' }}
        >
          <group
            name='RootNode_(model_correction_matrix)'
            scale={[0.60099334, 0.60099334, 0.60099334]}
            userData={{ name: 'RootNode (model correction matrix)' }}
          >
            <group name='root' userData={{ name: 'root' }}>
              <group
                name='GLTF_SceneRootNode'
                rotation={[Math.PI / 2, 0, 0]}
                userData={{ name: 'GLTF_SceneRootNode' }}
              >
                <group name='Cube_0' userData={{ name: 'Cube_0' }}>
                  <mesh
                    name='mesh_1'
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_1.geometry}
                    material={materials.hear}
                  />
                  <mesh
                    name='mesh_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_0.geometry}
                    material={materials.head}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/poly_head.gltf');
