/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shitlock_Homeless (https://sketchfab.com/Shitlock_Homeless)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spider-man-rigged-2f7ed879fedc46fb8814a3d6d2887fb1
title: Spider Man Rigged
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/spiderman.gltf');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    actions.Spidey.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} scale={0.005}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_7.geometry}
            material={materials.M_MED_Lateral_Body}
            skeleton={nodes.Object_7.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_8.geometry}
            material={materials.M_MED_Lateral_Mask}
            skeleton={nodes.Object_8.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/spiderman.gltf');
