/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/square-shift-3445ba90891146e8962b2d7260d35f2b
title: Square Shift
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/square_shift.gltf');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Animation?.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.22357368, 1.22357368, 1.22357368]}
          userData={{ name: 'Sketchfab_model' }}
        >
          <group name='root' userData={{ name: 'root' }}>
            <group
              name='GLTF_SceneRootNode'
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: 'GLTF_SceneRootNode' }}
            >
              <group
                name='Cube035_0'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.035_0' }}
              >
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={nodes.Object_4.material}
                  userData={{ name: 'Object_4' }}
                />
              </group>
              <group
                name='Cube036_2'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.036_2' }}
              >
                <group
                  name='FRAME017_1'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.017_1' }}
                >
                  <mesh
                    name='Object_8'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.material}
                    userData={{ name: 'Object_8' }}
                  />
                </group>
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={nodes.Object_6.material}
                  userData={{ name: 'Object_6' }}
                />
              </group>
              <group
                name='Cube037_5'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.037_5' }}
              >
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={nodes.Object_14.material}
                  userData={{ name: 'Object_14' }}
                />
              </group>
              <group
                name='Cube038_7'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.038_7' }}
              >
                <group
                  name='FRAME018_6'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.018_6' }}
                >
                  <mesh
                    name='Object_18'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials.material_2}
                    userData={{ name: 'Object_18' }}
                  />
                </group>
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={nodes.Object_16.material}
                  userData={{ name: 'Object_16' }}
                />
              </group>
              <group
                name='Cube039_10'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.039_10' }}
              >
                <mesh
                  name='Object_24'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={nodes.Object_24.material}
                  userData={{ name: 'Object_24' }}
                />
              </group>
              <group
                name='Cube040_12'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.040_12' }}
              >
                <group
                  name='FRAME019_11'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.019_11' }}
                >
                  <mesh
                    name='Object_28'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.material_3}
                    userData={{ name: 'Object_28' }}
                  />
                </group>
                <mesh
                  name='Object_26'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={nodes.Object_26.material}
                  userData={{ name: 'Object_26' }}
                />
              </group>
              <group
                name='Cube041_15'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.041_15' }}
              >
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={nodes.Object_34.material}
                  userData={{ name: 'Object_34' }}
                />
              </group>
              <group
                name='Cube042_17'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.042_17' }}
              >
                <group
                  name='FRAME020_16'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.020_16' }}
                >
                  <mesh
                    name='Object_38'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials.material_4}
                    userData={{ name: 'Object_38' }}
                  />
                </group>
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={nodes.Object_36.material}
                  userData={{ name: 'Object_36' }}
                />
              </group>
              <group
                name='Cube043_20'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.043_20' }}
              >
                <mesh
                  name='Object_44'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={nodes.Object_44.material}
                  userData={{ name: 'Object_44' }}
                />
              </group>
              <group
                name='Cube044_22'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.044_22' }}
              >
                <group
                  name='FRAME021_21'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.021_21' }}
                >
                  <mesh
                    name='Object_48'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_48.geometry}
                    material={materials.material_5}
                    userData={{ name: 'Object_48' }}
                  />
                </group>
                <mesh
                  name='Object_46'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={nodes.Object_46.material}
                  userData={{ name: 'Object_46' }}
                />
              </group>
              <group
                name='Cube045_25'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.045_25' }}
              >
                <mesh
                  name='Object_54'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={nodes.Object_54.material}
                  userData={{ name: 'Object_54' }}
                />
              </group>
              <group
                name='Cube046_27'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.046_27' }}
              >
                <group
                  name='FRAME022_26'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.022_26' }}
                >
                  <mesh
                    name='Object_58'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_58.geometry}
                    material={materials.material_6}
                    userData={{ name: 'Object_58' }}
                  />
                </group>
                <mesh
                  name='Object_56'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={nodes.Object_56.material}
                  userData={{ name: 'Object_56' }}
                />
              </group>
              <group
                name='Cube047_30'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.047_30' }}
              >
                <mesh
                  name='Object_64'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={nodes.Object_64.material}
                  userData={{ name: 'Object_64' }}
                />
              </group>
              <group
                name='Cube048_32'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.048_32' }}
              >
                <group
                  name='FRAME023_31'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.023_31' }}
                >
                  <mesh
                    name='Object_68'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={materials.material_7}
                    userData={{ name: 'Object_68' }}
                  />
                </group>
                <mesh
                  name='Object_66'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={nodes.Object_66.material}
                  userData={{ name: 'Object_66' }}
                />
              </group>
              <group
                name='Cube049_35'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.049_35' }}
              >
                <mesh
                  name='Object_74'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={nodes.Object_74.material}
                  userData={{ name: 'Object_74' }}
                />
              </group>
              <group
                name='Cube050_37'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.050_37' }}
              >
                <group
                  name='FRAME024_36'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.024_36' }}
                >
                  <mesh
                    name='Object_78'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_78.geometry}
                    material={materials.material_8}
                    userData={{ name: 'Object_78' }}
                  />
                </group>
                <mesh
                  name='Object_76'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={nodes.Object_76.material}
                  userData={{ name: 'Object_76' }}
                />
              </group>
              <group
                name='Cube051_40'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.051_40' }}
              >
                <mesh
                  name='Object_84'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={nodes.Object_84.material}
                  userData={{ name: 'Object_84' }}
                />
              </group>
              <group
                name='Cube052_42'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.052_42' }}
              >
                <group
                  name='FRAME025_41'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.025_41' }}
                >
                  <mesh
                    name='Object_88'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_88.geometry}
                    material={materials.material_9}
                    userData={{ name: 'Object_88' }}
                  />
                </group>
                <mesh
                  name='Object_86'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={nodes.Object_86.material}
                  userData={{ name: 'Object_86' }}
                />
              </group>
              <group
                name='Cube053_45'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.053_45' }}
              >
                <mesh
                  name='Object_94'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={nodes.Object_94.material}
                  userData={{ name: 'Object_94' }}
                />
              </group>
              <group
                name='Cube054_47'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.054_47' }}
              >
                <group
                  name='FRAME026_46'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.026_46' }}
                >
                  <mesh
                    name='Object_98'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_98.geometry}
                    material={materials.material_10}
                    userData={{ name: 'Object_98' }}
                  />
                </group>
                <mesh
                  name='Object_96'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={nodes.Object_96.material}
                  userData={{ name: 'Object_96' }}
                />
              </group>
              <group
                name='Cube055_50'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.055_50' }}
              >
                <mesh
                  name='Object_104'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={nodes.Object_104.material}
                  userData={{ name: 'Object_104' }}
                />
              </group>
              <group
                name='Cube056_52'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.056_52' }}
              >
                <group
                  name='FRAME027_51'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.027_51' }}
                >
                  <mesh
                    name='Object_108'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_108.geometry}
                    material={materials.material_11}
                    userData={{ name: 'Object_108' }}
                  />
                </group>
                <mesh
                  name='Object_106'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={nodes.Object_106.material}
                  userData={{ name: 'Object_106' }}
                />
              </group>
              <group
                name='Cube057_55'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.057_55' }}
              >
                <mesh
                  name='Object_114'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={nodes.Object_114.material}
                  userData={{ name: 'Object_114' }}
                />
              </group>
              <group
                name='Cube058_57'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.058_57' }}
              >
                <group
                  name='FRAME028_56'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.028_56' }}
                >
                  <mesh
                    name='Object_118'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_118.geometry}
                    material={materials.material_12}
                    userData={{ name: 'Object_118' }}
                  />
                </group>
                <mesh
                  name='Object_116'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={nodes.Object_116.material}
                  userData={{ name: 'Object_116' }}
                />
              </group>
              <group
                name='Cube059_60'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.059_60' }}
              >
                <mesh
                  name='Object_124'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={nodes.Object_124.material}
                  userData={{ name: 'Object_124' }}
                />
              </group>
              <group
                name='Cube060_62'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.060_62' }}
              >
                <group
                  name='FRAME029_61'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.029_61' }}
                >
                  <mesh
                    name='Object_128'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_128.geometry}
                    material={materials.material_13}
                    userData={{ name: 'Object_128' }}
                  />
                </group>
                <mesh
                  name='Object_126'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={nodes.Object_126.material}
                  userData={{ name: 'Object_126' }}
                />
              </group>
              <group
                name='Cube061_65'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.061_65' }}
              >
                <mesh
                  name='Object_134'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={nodes.Object_134.material}
                  userData={{ name: 'Object_134' }}
                />
              </group>
              <group
                name='Cube062_67'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.062_67' }}
              >
                <group
                  name='FRAME030_66'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.030_66' }}
                >
                  <mesh
                    name='Object_138'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_138.geometry}
                    material={materials.material_14}
                    userData={{ name: 'Object_138' }}
                  />
                </group>
                <mesh
                  name='Object_136'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={nodes.Object_136.material}
                  userData={{ name: 'Object_136' }}
                />
              </group>
              <group
                name='Cube063_70'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.063_70' }}
              >
                <mesh
                  name='Object_144'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={nodes.Object_144.material}
                  userData={{ name: 'Object_144' }}
                />
              </group>
              <group
                name='Cube064_72'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.064_72' }}
              >
                <group
                  name='FRAME031_71'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.031_71' }}
                >
                  <mesh
                    name='Object_148'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_148.geometry}
                    material={materials.material_15}
                    userData={{ name: 'Object_148' }}
                  />
                </group>
                <mesh
                  name='Object_146'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={nodes.Object_146.material}
                  userData={{ name: 'Object_146' }}
                />
              </group>
              <group
                name='Cube065_75'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.065_75' }}
              >
                <mesh
                  name='Object_154'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={nodes.Object_154.material}
                  userData={{ name: 'Object_154' }}
                />
              </group>
              <group
                name='Cube066_77'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.066_77' }}
              >
                <group
                  name='FRAME032_76'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.032_76' }}
                >
                  <mesh
                    name='Object_158'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials.material_16}
                    userData={{ name: 'Object_158' }}
                  />
                </group>
                <mesh
                  name='Object_156'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={nodes.Object_156.material}
                  userData={{ name: 'Object_156' }}
                />
              </group>
              <group
                name='Cube067_80'
                position={[1.00659168, 0, 0.01412807]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.067_80' }}
              >
                <mesh
                  name='Object_164'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_164.geometry}
                  material={nodes.Object_164.material}
                  userData={{ name: 'Object_164' }}
                />
              </group>
              <group
                name='Cube068_82'
                position={[0.0065918, 0, -0.97782612]}
                scale={[-0.15765476, -0.15765476, -0.15765476]}
                userData={{ name: 'Cube.068_82' }}
              >
                <group
                  name='FRAME033_81'
                  position={[-0.05103501, 0, -0.05178881]}
                  rotation={[-8e-8, Math.PI / 4, 3e-8]}
                  scale={[-8.47485447, 8.47485352, 8.47485447]}
                  userData={{ name: 'FRAME.033_81' }}
                >
                  <mesh
                    name='Object_168'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_168.geometry}
                    material={materials.material_17}
                    userData={{ name: 'Object_168' }}
                  />
                </group>
                <mesh
                  name='Object_166'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_166.geometry}
                  material={nodes.Object_166.material}
                  userData={{ name: 'Object_166' }}
                />
              </group>
              <group
                name='PIVIOT-2017_4'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.017_4' }}
              >
                <group
                  name='PIVIOT-1017_3'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.017_3' }}
                >
                  <mesh
                    name='Object_12'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={nodes.Object_12.material}
                    userData={{ name: 'Object_12' }}
                  />
                </group>
                <mesh
                  name='Object_10'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={nodes.Object_10.material}
                  userData={{ name: 'Object_10' }}
                />
              </group>
              <group
                name='PIVIOT-2018_9'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.018_9' }}
              >
                <group
                  name='PIVIOT-1018_8'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.018_8' }}
                >
                  <mesh
                    name='Object_22'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={nodes.Object_22.material}
                    userData={{ name: 'Object_22' }}
                  />
                </group>
                <mesh
                  name='Object_20'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={nodes.Object_20.material}
                  userData={{ name: 'Object_20' }}
                />
              </group>
              <group
                name='PIVIOT-2019_14'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.019_14' }}
              >
                <group
                  name='PIVIOT-1019_13'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.019_13' }}
                >
                  <mesh
                    name='Object_32'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={nodes.Object_32.material}
                    userData={{ name: 'Object_32' }}
                  />
                </group>
                <mesh
                  name='Object_30'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={nodes.Object_30.material}
                  userData={{ name: 'Object_30' }}
                />
              </group>
              <group
                name='PIVIOT-2020_19'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.020_19' }}
              >
                <group
                  name='PIVIOT-1020_18'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.020_18' }}
                >
                  <mesh
                    name='Object_42'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={nodes.Object_42.material}
                    userData={{ name: 'Object_42' }}
                  />
                </group>
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={nodes.Object_40.material}
                  userData={{ name: 'Object_40' }}
                />
              </group>
              <group
                name='PIVIOT-2021_24'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.021_24' }}
              >
                <group
                  name='PIVIOT-1021_23'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.021_23' }}
                >
                  <mesh
                    name='Object_52'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={nodes.Object_52.material}
                    userData={{ name: 'Object_52' }}
                  />
                </group>
                <mesh
                  name='Object_50'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={nodes.Object_50.material}
                  userData={{ name: 'Object_50' }}
                />
              </group>
              <group
                name='PIVIOT-2022_29'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.022_29' }}
              >
                <group
                  name='PIVIOT-1022_28'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.022_28' }}
                >
                  <mesh
                    name='Object_62'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_62.geometry}
                    material={nodes.Object_62.material}
                    userData={{ name: 'Object_62' }}
                  />
                </group>
                <mesh
                  name='Object_60'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={nodes.Object_60.material}
                  userData={{ name: 'Object_60' }}
                />
              </group>
              <group
                name='PIVIOT-2023_34'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.023_34' }}
              >
                <group
                  name='PIVIOT-1023_33'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.023_33' }}
                >
                  <mesh
                    name='Object_72'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_72.geometry}
                    material={nodes.Object_72.material}
                    userData={{ name: 'Object_72' }}
                  />
                </group>
                <mesh
                  name='Object_70'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={nodes.Object_70.material}
                  userData={{ name: 'Object_70' }}
                />
              </group>
              <group
                name='PIVIOT-2024_39'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.024_39' }}
              >
                <group
                  name='PIVIOT-1024_38'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.024_38' }}
                >
                  <mesh
                    name='Object_82'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_82.geometry}
                    material={nodes.Object_82.material}
                    userData={{ name: 'Object_82' }}
                  />
                </group>
                <mesh
                  name='Object_80'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={nodes.Object_80.material}
                  userData={{ name: 'Object_80' }}
                />
              </group>
              <group
                name='PIVIOT-2025_44'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.025_44' }}
              >
                <group
                  name='PIVIOT-1025_43'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.025_43' }}
                >
                  <mesh
                    name='Object_92'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_92.geometry}
                    material={nodes.Object_92.material}
                    userData={{ name: 'Object_92' }}
                  />
                </group>
                <mesh
                  name='Object_90'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_90.geometry}
                  material={nodes.Object_90.material}
                  userData={{ name: 'Object_90' }}
                />
              </group>
              <group
                name='PIVIOT-2026_49'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.026_49' }}
              >
                <group
                  name='PIVIOT-1026_48'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.026_48' }}
                >
                  <mesh
                    name='Object_102'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_102.geometry}
                    material={nodes.Object_102.material}
                    userData={{ name: 'Object_102' }}
                  />
                </group>
                <mesh
                  name='Object_100'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={nodes.Object_100.material}
                  userData={{ name: 'Object_100' }}
                />
              </group>
              <group
                name='PIVIOT-2027_54'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.027_54' }}
              >
                <group
                  name='PIVIOT-1027_53'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.027_53' }}
                >
                  <mesh
                    name='Object_112'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_112.geometry}
                    material={nodes.Object_112.material}
                    userData={{ name: 'Object_112' }}
                  />
                </group>
                <mesh
                  name='Object_110'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={nodes.Object_110.material}
                  userData={{ name: 'Object_110' }}
                />
              </group>
              <group
                name='PIVIOT-2028_59'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.028_59' }}
              >
                <group
                  name='PIVIOT-1028_58'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.028_58' }}
                >
                  <mesh
                    name='Object_122'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_122.geometry}
                    material={nodes.Object_122.material}
                    userData={{ name: 'Object_122' }}
                  />
                </group>
                <mesh
                  name='Object_120'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={nodes.Object_120.material}
                  userData={{ name: 'Object_120' }}
                />
              </group>
              <group
                name='PIVIOT-2029_64'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.029_64' }}
              >
                <group
                  name='PIVIOT-1029_63'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.029_63' }}
                >
                  <mesh
                    name='Object_132'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_132.geometry}
                    material={nodes.Object_132.material}
                    userData={{ name: 'Object_132' }}
                  />
                </group>
                <mesh
                  name='Object_130'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={nodes.Object_130.material}
                  userData={{ name: 'Object_130' }}
                />
              </group>
              <group
                name='PIVIOT-2030_69'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.030_69' }}
              >
                <group
                  name='PIVIOT-1030_68'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.030_68' }}
                >
                  <mesh
                    name='Object_142'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_142.geometry}
                    material={nodes.Object_142.material}
                    userData={{ name: 'Object_142' }}
                  />
                </group>
                <mesh
                  name='Object_140'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_140.geometry}
                  material={nodes.Object_140.material}
                  userData={{ name: 'Object_140' }}
                />
              </group>
              <group
                name='PIVIOT-2031_74'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.031_74' }}
              >
                <group
                  name='PIVIOT-1031_73'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.031_73' }}
                >
                  <mesh
                    name='Object_152'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_152.geometry}
                    material={nodes.Object_152.material}
                    userData={{ name: 'Object_152' }}
                  />
                </group>
                <mesh
                  name='Object_150'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_150.geometry}
                  material={nodes.Object_150.material}
                  userData={{ name: 'Object_150' }}
                />
              </group>
              <group
                name='PIVIOT-2032_79'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.032_79' }}
              >
                <group
                  name='PIVIOT-1032_78'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.032_78' }}
                >
                  <mesh
                    name='Object_162'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_162.geometry}
                    material={nodes.Object_162.material}
                    userData={{ name: 'Object_162' }}
                  />
                </group>
                <mesh
                  name='Object_160'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_160.geometry}
                  material={nodes.Object_160.material}
                  userData={{ name: 'Object_160' }}
                />
              </group>
              <group
                name='PIVIOT-2033_84'
                position={[-0.97740865, 0, 0.02217388]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-0.15765476, 0.15765476, 0.15765476]}
                userData={{ name: 'PIVIOT-2.033_84' }}
              >
                <group
                  name='PIVIOT-1033_83'
                  position={[6.24148607, 0, -6.34297562]}
                  userData={{ name: 'PIVIOT-1.033_83' }}
                >
                  <mesh
                    name='Object_172'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_172.geometry}
                    material={nodes.Object_172.material}
                    userData={{ name: 'Object_172' }}
                  />
                </group>
                <mesh
                  name='Object_170'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_170.geometry}
                  material={nodes.Object_170.material}
                  userData={{ name: 'Object_170' }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/square_shift.gltf');
