/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/square-shift-3445ba90891146e8962b2d7260d35f2b
title: Square Shift
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/square_shift.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    void actions.Animation.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.22}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_8.geometry}
                material={materials.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_18.geometry}
                material={materials.material_2}
              />
            </group>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_24.geometry}
              material={nodes.Object_24.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_28.geometry}
                material={materials.material_3}
              />
            </group>
            <mesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_34.geometry}
              material={nodes.Object_34.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_38.geometry}
                material={materials.material_4}
              />
            </group>
            <mesh
              geometry={nodes.Object_36.geometry}
              material={nodes.Object_36.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_44.geometry}
              material={nodes.Object_44.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_48.geometry}
                material={materials.material_5}
              />
            </group>
            <mesh
              geometry={nodes.Object_46.geometry}
              material={nodes.Object_46.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_54.geometry}
              material={nodes.Object_54.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_58.geometry}
                material={materials.material_6}
              />
            </group>
            <mesh
              geometry={nodes.Object_56.geometry}
              material={nodes.Object_56.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_64.geometry}
              material={nodes.Object_64.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_68.geometry}
                material={materials.material_7}
              />
            </group>
            <mesh
              geometry={nodes.Object_66.geometry}
              material={nodes.Object_66.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_74.geometry}
              material={nodes.Object_74.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_78.geometry}
                material={materials.material_8}
              />
            </group>
            <mesh
              geometry={nodes.Object_76.geometry}
              material={nodes.Object_76.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_84.geometry}
              material={nodes.Object_84.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_88.geometry}
                material={materials.material_9}
              />
            </group>
            <mesh
              geometry={nodes.Object_86.geometry}
              material={nodes.Object_86.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_94.geometry}
              material={nodes.Object_94.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_98.geometry}
                material={materials.material_10}
              />
            </group>
            <mesh
              geometry={nodes.Object_96.geometry}
              material={nodes.Object_96.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_104.geometry}
              material={nodes.Object_104.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_108.geometry}
                material={materials.material_11}
              />
            </group>
            <mesh
              geometry={nodes.Object_106.geometry}
              material={nodes.Object_106.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_114.geometry}
              material={nodes.Object_114.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_118.geometry}
                material={materials.material_12}
              />
            </group>
            <mesh
              geometry={nodes.Object_116.geometry}
              material={nodes.Object_116.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_124.geometry}
              material={nodes.Object_124.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_128.geometry}
                material={materials.material_13}
              />
            </group>
            <mesh
              geometry={nodes.Object_126.geometry}
              material={nodes.Object_126.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_134.geometry}
              material={nodes.Object_134.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_138.geometry}
                material={materials.material_14}
              />
            </group>
            <mesh
              geometry={nodes.Object_136.geometry}
              material={nodes.Object_136.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_144.geometry}
              material={nodes.Object_144.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_148.geometry}
                material={materials.material_15}
              />
            </group>
            <mesh
              geometry={nodes.Object_146.geometry}
              material={nodes.Object_146.material}
            />
          </group>
          <group position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_154.geometry}
              material={nodes.Object_154.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_158.geometry}
                material={materials.material_16}
              />
            </group>
            <mesh
              geometry={nodes.Object_156.geometry}
              material={nodes.Object_156.material}
            />
          </group>
          <group name='Cube067_80' position={[1.01, 0, 0.01]} scale={-0.16}>
            <mesh
              geometry={nodes.Object_164.geometry}
              material={nodes.Object_164.material}
            />
          </group>
          <group position={[0.01, 0, -0.98]} scale={-0.16}>
            <group
              position={[-0.05, 0, -0.05]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[-8.47, 8.47, 8.47]}
            >
              <mesh
                geometry={nodes.Object_168.geometry}
                material={materials.material_17}
              />
            </group>
            <mesh
              geometry={nodes.Object_166.geometry}
              material={nodes.Object_166.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_12.geometry}
                material={nodes.Object_12.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_22.geometry}
                material={nodes.Object_22.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_32.geometry}
                material={nodes.Object_32.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={nodes.Object_30.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_42.geometry}
                material={nodes.Object_42.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_40.geometry}
              material={nodes.Object_40.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_52.geometry}
                material={nodes.Object_52.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_50.geometry}
              material={nodes.Object_50.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_62.geometry}
                material={nodes.Object_62.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_60.geometry}
              material={nodes.Object_60.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_72.geometry}
                material={nodes.Object_72.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={nodes.Object_70.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_82.geometry}
                material={nodes.Object_82.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_80.geometry}
              material={nodes.Object_80.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_92.geometry}
                material={nodes.Object_92.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_90.geometry}
              material={nodes.Object_90.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_102.geometry}
                material={nodes.Object_102.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_100.geometry}
              material={nodes.Object_100.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_112.geometry}
                material={nodes.Object_112.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_110.geometry}
              material={nodes.Object_110.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_122.geometry}
                material={nodes.Object_122.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_120.geometry}
              material={nodes.Object_120.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_132.geometry}
                material={nodes.Object_132.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_130.geometry}
              material={nodes.Object_130.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_142.geometry}
                material={nodes.Object_142.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_140.geometry}
              material={nodes.Object_140.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_152.geometry}
                material={nodes.Object_152.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_150.geometry}
              material={nodes.Object_150.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_162.geometry}
                material={nodes.Object_162.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_160.geometry}
              material={nodes.Object_160.material}
            />
          </group>
          <group
            position={[-0.98, 0, 0.02]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-0.16, 0.16, 0.16]}
          >
            <group position={[6.24, 0, -6.34]}>
              <mesh
                geometry={nodes.Object_172.geometry}
                material={nodes.Object_172.material}
              />
            </group>
            <mesh
              geometry={nodes.Object_170.geometry}
              material={nodes.Object_170.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/square_shift.gltf');
